// data.js
export const hotels = [
    {
      id: 1,
      name: 'Oceanview Resort',
      location: 'Miami Beach, FL',
      price: '$250/night',
      description: 'Escape to the Oceanview Resort, where luxury meets the sea.',
      image: 'https://picsum.photos/id/1018/600/400',
    },
    {
      id: 2,
      name: 'Mountain Escape Lodge',
      location: 'Aspen, CO',
      price: '$300/night',
      description: 'Nestled in the heart of Aspen, enjoy serene mountain views.',
      image: 'https://picsum.photos/id/1015/600/400',
    },
    {
      id: 3,
      name: 'Desert Mirage Inn',
      location: 'Sedona, AZ',
      price: '$200/night',
      description: 'A tranquil retreat in the red rocks of Sedona.',
      image: 'https://picsum.photos/id/1019/600/400',
    },
    {
      id: 4,
      name: 'Lakeside Retreat',
      location: 'Lake Tahoe, CA',
      price: '$350/night',
      description: 'Experience luxury lakeside living with breathtaking views.',
      image: 'https://picsum.photos/id/1020/600/400',
    },
    {
      id: 5,
      name: 'Cityscape Hotel',
      location: 'New York, NY',
      price: '$400/night',
      description: 'Stay in the heart of the city with skyline views.',
      image: 'https://picsum.photos/id/1021/600/400',
    },
    {
      id: 6,
      name: 'Seaside Escape',
      location: 'Santa Monica, CA',
      price: '$275/night',
      description: 'Enjoy the sun and surf at this beachfront property.',
      image: 'https://picsum.photos/id/1022/600/400',
    },
    {
      id: 7,
      name: 'Countryside Inn',
      location: 'Napa Valley, CA',
      price: '$225/night',
      description: 'Relax in the rolling hills of wine country.',
      image: 'https://picsum.photos/id/1023/600/400',
    },
    {
      id: 8,
      name: 'Urban Oasis',
      location: 'Chicago, IL',
      price: '$275/night',
      description: 'A modern hotel in the bustling city center.',
      image: 'https://picsum.photos/id/1024/600/400',
    },
    {
      id: 9,
      name: 'Island Breeze Resort',
      location: 'Key West, FL',
      price: '$350/night',
      description: 'A tropical paradise with island charm.',
      image: 'https://picsum.photos/id/1025/600/400',
    },
    {
      id: 10,
      name: 'Alpine Lodge',
      location: 'Aspen, CO',
      price: '$320/night',
      description: 'Ski-in/ski-out access with cozy mountain vibes.',
      image: 'https://picsum.photos/id/1026/600/400',
    },
    {
      id: 11,
      name: 'Beachfront Bliss',
      location: 'Malibu, CA',
      price: '$450/night',
      description: 'Luxury living steps from the Pacific Ocean.',
      image: 'https://picsum.photos/id/1027/600/400',
    },
    {
      id: 12,
      name: 'Forest Hideaway',
      location: 'Olympic National Park, WA',
      price: '$280/night',
      description: 'A secluded cabin surrounded by lush forest.',
      image: 'https://picsum.photos/id/1028/600/400',
    },
  ];
  